const data = [
  {
    id: 1,
    filename: "Install-gcc-on-ubuntu-from-source.md",
    title: "通过源码安装最新版gcc",
    excerpt: "在新安装的ubuntu系统上，通过源码，安装最新版的gcc",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Linux/2.jpg",
    category: "Tools",
    date: "23 Aug 2022",
    tags: ["gcc", "ubuntu", "Linux"],
  },
  {
    id: 2,
    filename:"builtin-functions-in-C-and-Cpp.md",
    title: "几个常用的C/C++builtin函数",
    excerpt: "介绍几个工作中好用且常用的几个C和C++的builtin函数",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/1.jpg",
    category: "Programming",
    date: "26 Aug 2022",
    tags: ["C", "C++", "clang", "gcc"],
  },
  {
    id: 3,
    filename:"eleminate-warning-in-Cpp.md",
    title: "C++消除warning",
    excerpt: "我们写的程序出现的warning可能无法避免，此时，我们可以在代码中加入一些内容消除这些warning。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/5.jpg",
    category: "Programming",
    date: "4 Sep 2022",
    tags: ["C++", "clang", "gcc"],
  },
  {
    id: 4,
    filename:"likely-and-unlikely-in-cpp.md",
    title: "近距离观察C++20`[[likely]]`和`[[unlikely]]`属性",
    excerpt: "C++20引入了两个新的属性`[[likely]]`和`[[unlikely]]`，这两个属性可以帮助编译器优化代码，这一篇来观察一下对应的汇编代码。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/3.jpg",
    category: "Programming",
    date: "13 Sep 2022",
    tags: ["C++", "Assembly"],
  },
  {
    id: 5,
    filename:"Matchif-in-Cpp.md",
    title: "C++模板实现MatchIf",
    excerpt: "利用C++模板技巧，实现matchif语句。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/4.jpg",
    category: "Programming",
    date: "21 Sep 2022",
    tags: ["C++"],
  },
  {
    id: 6,
    filename:"tricks-of-C-macro-1.md",
    title: "C宏技巧 --- 根据宏参数个数不同采取不同动作",
    excerpt: "有的时候我们希望当宏参数不同时，C语言能够采取不同的动作，例如只有一个参数时，扩展成一个if，当有两个参数时，扩展成一个if和一个else if。实际上使用一些技巧完全可以让C宏做到这件事。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/5.jpg",
    category: "Programming",
    date: "3 Oct 2022",
    tags: ["C"],
  },
  {
    id: 7,
    filename:"Annual-Summary-2023.md",
    title: "2023年度总结",
    excerpt: "2023年过完啦，做一个年度总结。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Picked/2023-annual.jpg",
    category: "PersonalGrowth",
    date: "21 Jan 2024",
    tags: ["AnnualSummary"],
  },
  {
    id: 8,
    filename:"from-valarry-to-simd-Cpp.md",
    title: "C++ - 从valarry到simd",
    excerpt: "很久以前，C++就有支持运算符操作的valarray了，C++23之后会有simd，实际上运算符的问题相当复杂，值得探讨一下",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/7.jpg",
    category: "Programming",
    date: "16 Oct 2022",
    tags: ["C++"],
  },
  {
    id: 9,
    filename:"CRTP-Cpp.md",
    title: "C++的静态继承 - CRTP机制",
    excerpt: "面向对象中的继承机制要依赖动态多态来实现，不过C++的CRTP机制允许我们进行静态继承",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/1.jpg",
    category: "Programming",
    date: "27 Oct 2022",
    tags: ["C++"],
  },
  {
    id: 10,
    filename:"black-magin-Compile-time-mutable-in-Cpp.md",
    title: "C++黑魔法 - 编译期变量",
    excerpt: "编译期变量目前实际上在C++里是不存在的概念，因为C++的模板编程是函数式范式，但是其实可以利用C++编译器的漏洞来间接做到，所以是黑魔法，这里仅仅做有趣的探讨。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/6.jpg",
    category: "Principle",
    date: "4 Nov 2022",
    tags: ["C++"],
  },
  {
    id: 11,
    filename:"limited-parameters-of-temp-temp-in-cpp.md",
    title: "限制C++中的模板模板参数",
    excerpt: "C++的模板参数比较好限制，但是模板模板参数似乎有一点难，这里做一个记录",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/3.jpg",
    category: "Programming",
    date: "12 Nov 2022",
    tags: ["C++"],
  },
  {
    id: 12,
    filename:"share-command-line-in-linux.md",
    title: "在linux上远程分享命令行",
    excerpt: "不使用那些付费的软件，仅仅使用tmux和ssh两个工具，就可以在两台机器上远程共享命令行。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Linux/2.jpg",
    category: "Tools",
    date: "21 Nov 2022",
    tags: ["Linux"],
  },
  {
    id: 13,
    filename:"Simple-format-in-Cpp11.md",
    title: "C++11上的简单format函数",
    excerpt: "C++20引入了std::format，但是如果我们不得不在低版本的C++上工作，而且又无法使用外部库的话，那不如自己来写一个吧。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/4.jpg",
    category: "Programming",
    date: "23 Dec 2022",
    tags: ["C++"],
  },
  {
    id: 14,
    filename:"glibc-libm-isinf.md",
    title: "glibc源码剖析 - isinf",
    excerpt: "剖析一下glibc中isinf的实现，虽然是很简单的函数，但也有很值得学习的地方",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Math/1.jpg",
    category: "Principle",
    date: "11 Jan 2023",
    tags: ["C", "glibc"],
  },
  {
    id: 15,
    filename:"glibc-libm-logf.md",
    title: "glibc源码剖析 - logf",
    excerpt: "剖析一下glibc中logf的实现，这个代码的解读需要不少数学知识",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Math/2.jpg",
    category: "Principle",
    date: "26 Jan 2023",
    tags: ["C", "glibc"],
  },
  {
    id: 16,
    filename:"glibc-libm-scalbnf.md",
    title: "glibc源码剖析 - scalbnf",
    excerpt: "剖析一下glibc中scalbnf的实现，熟悉IEEE 754标准才能解读好这个代码",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Math/3.jpg",
    category: "Principle",
    date: "3 Feb 2023",
    tags: ["C", "glibc"],
  },
  {
    id: 17,
    filename:"Cpp-Cached-function.md",
    title: "在C++中编写Cached函数",
    excerpt: "python里面有一个超好用的cache关键字，可以用来提升性能，C++虽然没有这样的东西，但是我们可以来自己实现",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Math/4.jpg",
    category: "Programming",
    date: "9 Feb 2023",
    tags: ["C++"],
  },
  {
    id: 18,
    filename:"cuda-libdevice-logf.md",
    title: "cuda libdevice中的logf函数",
    excerpt: "glibc的logf虽然比较精准，但不太适合在gpu这种向量化架构上跑，看看cuda是怎么计算的",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Math/5.jpg",
    category: "Principle",
    date: "9 Feb 2023",
    tags: ["C++"],
  },
  {
    id: 19,
    filename:"MBTI的另一种用法.md",
    title: "MBTI的另一种用法",
    excerpt: "MBTI仅仅是一种玄学分析吗？",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-1.jpg",
    category: "PersonalGrowth",
    date: "21 Dec 2023",
    tags: ["Thoughts"],
  },
  {
    id: 20,
    filename:"什么才是真正的幸运.md",
    title: "什么才是真正的幸运",
    excerpt: "赚大钱，不劳而获，是幸运吗？",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-2.jpg",
    category: "PersonalGrowth",
    date: "28 Dec 2023",
    tags: ["Thoughts"],
  },
  {
    id: 21,
    filename:"认真对待投资投机.md",
    title: "认真对待投资投机",
    excerpt: "如果真的想要在市场上挣到钱，就应当将投机视为一门严肃的生意，并诚心敬业，不可以自贬身价向门外汉看齐。许多门外汉想也不想，便将投机看成单纯的赌博。  --- 利弗莫尔",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Trade/1.jpg",
    category: "PersonalGrowth",
    date: "2 Jan 2024",
    tags: ["Thoughts", "Trading"],
  },
  {
    id: 22,
    filename:"技术分析是有用的吗.md",
    title: "技术分析是有用的吗",
    excerpt: "技术分析的精髓在于判断市场状态，而并非如很多散户所言预测市场。许多散户想也不想，就把技术分析当作是彩票的玄学分析，这实际上仅仅是一种偏见而已。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Trade/2.jpg",
    category: "PersonalGrowth",
    date: "7 Jan 2024",
    tags: ["Thoughts", "Trading"],
  },
  {
    id: 23,
    filename:"Experience-of-learning-English.md",
    title: "分享一些学英语的经验",
    excerpt: "来源于我的知乎回答：大量阅读英文是否是学英语的好方法",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-2.jpg",
    category: "PersonalGrowth",
    date: "11 Jan 2024",
    tags: ["EnglishLearning"],
  },
  {
    id: 24,
    filename:"The-meaning-of-learning-English.md",
    title: "学英语的意义",
    excerpt: "来源于我的知乎回答：学英语有什么意义",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-3.jpg",
    category: "PersonalGrowth",
    date: "17 Jan 2024",
    tags: ["EnglishLearning"],
  },
  {
    id: 25,
    filename:"Trading-principles.md",
    title: "我的交易纪律",
    excerpt: "做交易，技术和技能实际上还在其次，最重要的是要有纪律，避免凭借情绪和冲动来开单。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Trade/3.jpg",
    category: "PersonalGrowth",
    date: "22 Jan 2024",
    tags: ["Thoughts", "Trading"],
  },
];

export default data;

