const data = [
  {
    id: 7,
    filename:"Annual-Summary-2023.md",
    title: "2023年度总结",
    excerpt: "2023年过完啦，做一个年度总结。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Picked/2023-annual.jpg",
    category: "PersonalGrowth",
    date: "21 Jan 2024",
    tags: ["AnnualSummary"],
  },
  {
    id: 22,
    filename:"技术分析是有用的吗.md",
    title: "技术分析是有用的吗",
    excerpt: "技术分析的精髓在于判断市场状态，而并非如很多散户所言预测市场。许多散户想也不想，就把技术分析当作是彩票的玄学分析，这实际上仅仅是一种偏见而已。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Trade/2.jpg",
    category: "PersonalGrowth",
    date: "7 Jan 2024",
    tags: ["Thoughts", "Trading"],
  },
  {
    id: 24,
    filename:"The-meaning-of-learning-English.md",
    title: "学英语的意义",
    excerpt: "来源于我的知乎回答：学英语有什么意义",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-3.jpg",
    category: "PersonalGrowth",
    date: "17 Jan 2024",
    tags: ["EnglishLearning"],
  },
  {
    id: 20,
    filename:"什么才是真正的幸运.md",
    title: "什么才是真正的幸运",
    excerpt: "赚大钱，不劳而获，是幸运吗？",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-2.jpg",
    category: "PersonalGrowth",
    date: "28 Dec 2023",
    tags: ["Thoughts"],
  },
  {
    id: 25,
    filename:"Stock-Masterpiece-hand-manipulator-technique.md",
    title: "股票大作手操盘术 - 摘抄",
    excerpt: "100年前的杰西·利弗莫尔在上世纪的美国股市赚到了上亿的财富，虽然现在的许多细节已经不再适用，但他的许多思想仍然值得现代人借鉴。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Trade/5.jpg",
    category: "TradingThoughts",
    date: "22 Jan 2024",
    tags: ["Thought"],
  },
];

export default data;
