const data = [
  {
    id: 7,
    filename:"Annual-Summary-2023.md",
    title: "2023年度总结",
    excerpt: "2023年过完啦，做一个年度总结。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Picked/2023-annual.jpg",
    category: "PersonalGrowth",
    date: "21 Jan 2024",
    tags: ["AnnualSummary"],
  },
  {
    id: 22,
    filename:"技术分析是有用的吗.md",
    title: "技术分析是有用的吗",
    excerpt: "技术分析的精髓在于判断市场状态，而并非如很多散户所言预测市场。许多散户想也不想，就把技术分析当作是彩票的玄学分析，这实际上仅仅是一种偏见而已。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Trade/2.jpg",
    category: "PersonalGrowth",
    date: "7 Jan 2024",
    tags: ["Thoughts", "Trading"],
  },
  {
    id: 10,
    filename:"black-magin-Compile-time-mutable-in-Cpp.md",
    title: "C++黑魔法 - 编译期变量",
    excerpt: "编译期变量目前实际上在C++里是不存在的概念，因为C++的模板编程是函数式范式，但是其实可以利用C++编译器的漏洞来间接做到，所以是黑魔法，这里仅仅做有趣的探讨。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/2.jpg",
    category: "Principle",
    date: "4 Nov 2022",
    tags: ["C++"],
  },
  {
    id: 20,
    filename:"什么才是真正的幸运.md",
    title: "什么才是真正的幸运",
    excerpt: "赚大钱，不劳而获，是幸运吗？",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Life/cabin-3.jpg",
    category: "PersonalGrowth",
    date: "28 Dec 2023",
    tags: ["Thoughts"],
  },
  {
    id: 5,
    filename:"Matchif-in-Cpp.md",
    title: "C++模板实现MatchIf",
    excerpt: "利用C++模板技巧，实现matchif语句。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/4.jpg",
    category: "Programming",
    date: "21 Sep 2022",
    tags: ["C++"],
  },
];

export default data;
