const data = [
  {
    id: 1,
    filename:"Annual-Summary-2023.md",
    title: "2023年度总结",
    excerpt: "2023年过完啦，做一个年度总结。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Picked/2023-annual.jpg",
    category: "PersonalGrowth",
    date: "21 Jan 2024",
    tags: ["AnnualSummary"],
  },
  {
    id: 2,
    filename:"builtin-functions-in-C-and-Cpp.md",
    title: "几个常用的C/C++builtin函数",
    excerpt: "介绍几个工作中好用且常用的几个C和C++的builtin函数",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/1.jpg",
    category: "Programming",
    date: "26 Aug 2022",
    tags: ["C", "C++", "clang", "gcc"],
  },
  {
    id: 3,
    filename:"eleminate-warning-in-Cpp.md",
    title: "C++消除warning",
    excerpt: "我们写的程序出现的warning可能无法避免，此时，我们可以在代码中加入一些内容消除这些warning。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/2.jpg",
    category: "Programming",
    date: "4 Sep 2022",
    tags: ["C++", "clang", "gcc"],
  },
  {
    id: 4,
    filename:"likely-and-unlikely-in-cpp.md",
    title: "近距离观察C++20`[[likely]]`和`[[unlikely]]`属性",
    excerpt: "C++20引入了两个新的属性`[[likely]]`和`[[unlikely]]`，这两个属性可以帮助编译器优化代码，这一篇来观察一下对应的汇编代码。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/3.jpg",
    category: "Programming",
    date: "13 Sep 2022",
    tags: ["C++", "Assembly"],
  },
  {
    id: 5,
    filename:"Matchif-in-Cpp.md",
    title: "C++模板实现MatchIf",
    excerpt: "利用C++模板技巧，实现matchif语句。",
    img: "https://blogimgs-1309485105.cos.ap-nanjing.myqcloud.com/Cover/Cpp/4.jpg",
    category: "Programming",
    date: "21 Sep 2022",
    tags: ["C++"],
  },
];

export default data;
